server:
  port: 9191


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authDB?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
